source/AccumVacf.c File Reference
#include <stdio.h>
#include "global.h"
Functions
double Integrate (double *, int)
void PrintVacf ()
void ZeroVacf ()
void AccumVacf ()
Function Documentation
AccumVacf()
void AccumVacf ()
Definition at line 27 of file AccumVacf.c.
                 {
 double fac;
 int j, nb;
 for(nb = 1 ; nb <= nBuffAcf ; nb ++){
  if(indexAcf[nb] == nValAcf){
   for(j = 1 ; j <= nValAcf; j ++){
    viscAcfAv[j] += viscAcf[nb][j];
    }
  indexAcf[nb] = 0;
  countAcfAv ++;
  if(countAcfAv == limitAcfAv){
   fac = 1./(kinEnergy*region[1]*region[2]*limitAcfAv);
   viscAcfInt = fac*stepAcf*deltaT*Integrate(viscAcfAv, nValAcf);
   PrintVacf();
   ZeroVacf();
} } } }
References countAcfAv, deltaT, indexAcf, Integrate(), kinEnergy, limitAcfAv, nBuffAcf, nValAcf, PrintVacf(), region, stepAcf, viscAcf, viscAcfAv, viscAcfInt, and ZeroVacf().
Referenced by EvalVacf().
Integrate()
double Integrate (double * f, int nf)
Definition at line 25 of file Integrate.c.
                                   {
 double s;
 int i;
 s = 0.5*(f[1] + f[nf]);
 for(i = 2 ; i <= nf - 1 ; i ++)
  s += f[i];
 return(s);
}
Referenced by AccumVacf().
PrintVacf()
void PrintVacf ()
Definition at line 25 of file PrintVacf.c.
                {
 double tVal;
 int j;
 fprintf(fpvisc,"viscosity acf\n");
 for(j = 1 ; j <= nValAcf ; j ++){
  tVal = (j-1)*stepAcf*deltaT;
  fprintf(fpvisc, "%lf\t %lf\t %lf\n", tVal, viscAcfAv[j], viscAcfAv[j]/viscAcfAv[1]);
  }
 fprintf(fpvisc, "viscosity acf integral : %lf\n", viscAcfInt);
}
References deltaT, fpvisc, nValAcf, stepAcf, viscAcfAv, and viscAcfInt.
Referenced by AccumVacf().
ZeroVacf()
void ZeroVacf ()
Definition at line 25 of file ZeroVacf.c.
               {
 int j;
 countAcfAv= 0 ;
 for(j = 1 ; j <= nValAcf ; j ++)
  viscAcfAv[j] = 0.;
}
References countAcfAv, nValAcf, and viscAcfAv.
Referenced by AccumVacf().