source/InitVacf.c File Reference
#include <stdio.h>
#include "global.h"
Functions
void ZeroVacf ()
void InitVacf ()
Function Documentation
InitVacf()
void InitVacf ()
Definition at line 26 of file InitVacf.c.
               {
  int nb;
  for(nb = 1 ; nb <= nBuffAcf ; nb ++)
    indexAcf[nb] = -(nb-1)*nValAcf/nBuffAcf;
  ZeroVacf();
}
References indexAcf, nBuffAcf, nValAcf, and ZeroVacf().
Referenced by SetupJob().
ZeroVacf()
void ZeroVacf ()
Definition at line 25 of file ZeroVacf.c.
               {
 int j;
 countAcfAv= 0 ;
 for(j = 1 ; j <= nValAcf ; j ++)
  viscAcfAv[j] = 0.;
}
Referenced by InitVacf().