source/SetupJob.c File Reference
#include <stdio.h>
#include "global.h"
Functions
void AllocArrays ()
void AccumProps (int icode)
void InitVacf ()
void SetupJob ()
Function Documentation
AccumProps()
void AccumProps (int icode)
Definition at line 25 of file AccumProps.c.
                          {
 if(icode == 0){
 sPotEnergy = ssPotEnergy = 0.;
 sKinEnergy = ssKinEnergy = 0.;
 sPressure = ssPressure = 0.;
 sTotEnergy = ssTotEnergy = 0.;
 svirSum = 0.;
 }else if(icode == 1){
 sPotEnergy += potEnergy;
 ssPotEnergy += Sqr(potEnergy);
 sKinEnergy += kinEnergy;
 ssKinEnergy += Sqr(kinEnergy);
 sTotEnergy += totEnergy;
 ssTotEnergy += Sqr(totEnergy);
 sPressure += pressure;
 ssPressure += Sqr(pressure);
 svirSum += virSum;
 }else if(icode == 2){
 sPotEnergy /= stepAvg;
 ssPotEnergy /= sqrt(ssPotEnergy/stepAvg - Sqr(sPotEnergy));
 sTotEnergy /= stepAvg;
 ssTotEnergy = sqrt(ssTotEnergy/stepAvg - Sqr(sTotEnergy));
 sKinEnergy /= stepAvg;
 ssKinEnergy = sqrt(ssKinEnergy/stepAvg - Sqr(sKinEnergy));
 sPressure /= stepAvg;
 ssPressure = sqrt(ssPressure/stepAvg - Sqr(sPressure));
 svirSum /= stepAvg;
 } }
References kinEnergy, potEnergy, pressure, sKinEnergy, sPotEnergy, sPressure, Sqr, ssKinEnergy, ssPotEnergy, ssPressure, ssTotEnergy, stepAvg, sTotEnergy, svirSum, totEnergy, and virSum.
Referenced by SetupJob().
AllocArrays()
void AllocArrays ()
Definition at line 25 of file AllocArrays.c.
                  {
 int n;
 // SPACETIME CORRELATIONS
 cfOrg = (double **) malloc ((nBuffCorr+1)*sizeof(double *));
 for (n = 0; n <= nBuffCorr; n++)
  cfOrg[n] = (double *) malloc ((2*nFunCorr+1)*sizeof(double));
  
 cfVal = (double *) malloc ((2*nFunCorr+1)*sizeof(double));
 indexCorr = (int *) malloc ((nBuffCorr+1)*sizeof(int));
 
 spacetimeCorr = (double **) malloc ((nBuffCorr+1)*sizeof(double));
 for (n = 0; n <= nBuffCorr; n++)
 spacetimeCorr[n] = (double *) malloc ((nFunCorr*nValCorr+1)*sizeof(double));
 
 spacetimeCorrAv = (double *) malloc ((nFunCorr*nValCorr+1)*sizeof(double));
 // VISCOSITY
 indexAcf = (double *)malloc((nBuffAcf+1)*sizeof(double));
 viscAcf = (double **)malloc((nBuffAcf+1)*sizeof(double *));
 for(n = 0 ; n <= nBuffAcf ; n ++)
  viscAcf[n] = (double *)malloc((nValAcf+1)*sizeof(double));
 
 viscAcfOrg = (double *)malloc((nBuffAcf+1)*sizeof(double));
 viscAcfAv = (double *)malloc((nValAcf+1)*sizeof(double));
  // RDF
  histRdf = (double *)malloc((sizeHistRdf+1)*sizeof(double));
}
References cfOrg, cfVal, histRdf, indexAcf, indexCorr, nBuffAcf, nBuffCorr, nFunCorr, nValAcf, nValCorr, sizeHistRdf, spacetimeCorr, spacetimeCorrAv, viscAcf, viscAcfAv, and viscAcfOrg.
Referenced by SetupJob().
InitVacf()
void InitVacf ()
Definition at line 26 of file InitVacf.c.
               {
  int nb;
  for(nb = 1 ; nb <= nBuffAcf ; nb ++)
    indexAcf[nb] = -(nb-1)*nValAcf/nBuffAcf;
  ZeroVacf();
}
References indexAcf, nBuffAcf, nValAcf, and ZeroVacf().
Referenced by SetupJob().
SetupJob()
void SetupJob ()
Definition at line 27 of file SetupJob.c.
               {
  AllocArrays();
  AccumProps(0);
  InitVacf();
  stepCount = 0;
  // INITIALISE SPACETIME CORRELATIONS
  int n;
  for (n = 1; n <= nBuffCorr; n++)
    indexCorr[n] = -(n - 1)*nValCorr/nBuffCorr;
  
  countCorrAv = 0.;
  for (n = 1; n <= nFunCorr*nValCorr; n++)
    spacetimeCorrAv[n] = 0.;
  //RDF
  countRdf = 0;
}
References AccumProps(), AllocArrays(), countCorrAv, countRdf, indexCorr, InitVacf(), nBuffCorr, nFunCorr, nValCorr, spacetimeCorrAv, and stepCount.
Referenced by main().