name: CI Build and Test with MPI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential mpich libmpich-dev

    - name: Build source code
      run: |
        cd source
        make clean
        make
        ./main test
        
    - name: Build and run unit tests with MPI
      run: |
        cd unittest
        make clean
        make run
        

